### ISSUE TITLE
UI/UX: passwordless ssh for all nodes

### ISSUE THREAD

**Issue by zzhou1** [ganghe/o2locktop#1]
check and guide user to config passwordless ssh for all nodes

server-out-side-of-cluster> ./o2locktop -n node1:/mnt/shared -n node2 -n node3

Ideally, the intuitive tool should check passwordless ssh for all nodes, otherwise guide user with ssh-copy-id commands. At lease, provide user the knowledge to run prepared commands, ie,

server-out-side-of-cluster> ssh-copy-id root@node1
server-out-side-of-cluster> ssh-copy-id root@node2
server-out-side-of-cluster> ssh-copy-id root@node3

**Comment by ganghe** [comment]
Fixed it, please see the commit,
commit fb494db8ad7d88490ce47e1e51b9a0e4273af902
Author: Gang He <ghe@suse.com>
Date:   Fri Feb 15 16:05:47 2019 +0800
