### ISSUE TITLE
When the number of locks is too big, the tool will get stuck

### ISSUE THREAD

**Issue by brewHouses** [ganghe/o2locktop#36]
I create 1,000,000 files on ocfs2 file system, and cat the locking_stat file, There is almost 500,000 item in the file. But the tool get stuck. I use o2locktop in remote mode and I check the cat option that executed by ssh, it takes about 15s. Then it takes about 2 hours to decode the locking_stat file which is unbearable. 
And we should check the python sort method and the sort method in the tools to compare and get the good one.
What's more, when process too large number of locks. The CPU usage rate will up to 98%, and memory usage rate will up to 40%.

**Comment by ganghe** [comment]
The kernel patches will fix this problem.
https://ozlabs.org/~akpm/mmots/broken-out/ocfs2-add-last-unlock-times-in-locking_state.patch https://ozlabs.org/~akpm/mmots/broken-out/ocfs2-add-locking-filter-debugfs-file.patch 
https://ozlabs.org/~akpm/mmots/broken-out/ocfs2-add-locking-filter-debugfs-file-fix.patch 
https://ozlabs.org/~akpm/mmots/broken-out/ocfs2-add-first-lock-wait-time-in-locking_state.patch

Thanks
Gang
